export const state = {
  gapiScriptReady: false,
  gisScriptReady: false,
  gapiClientReady: false,
  tokenClient: null,
  dbMusics: [],
  dbDiffs: [],
  allRecords: [],
  filteredRecords: [],
  isSelectMode: false,
  selectedIds: new Set(),
  showBestOnly: false,
  currentMode: "upload",
  editorQueue: [],
  activeItemId: null,
  settings: null,
  currentDeviceKey: "default",
  driveCache: {
    folderLookup: new Map(),
    rootFolder: null,
    fcFolder: null,
    songFolderByKey: new Map(),
  },
};
